name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tmcarrara/react-test-up -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true tmcarrara/react-test-up npm test

      - run: docker build -t tmcarrara/multi-client-up ./client
      - run: docker build -t tmcarrara/multi-nginx-up ./nginx
      - run: docker build -t tmcarrara/multi-server-up ./server
      - run: docker build -t tmcarrara/multi-worker-up ./worker

      - run: docker push tmcarrara/multi-client-up
      - run: docker push tmcarrara/multi-nginx-up
      - run: docker push tmcarrara/multi-server-up
      - run: docker push tmcarrara/multi-worker-up

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multi-gh-env
          # existing_bucket_name: elasticbeanstalk-us-east-1-537273373900
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
